### ISSUE TITLE
Xdebug config is not set correctly

### ISSUE THREAD

**Issue by otakumike** [ironstar-io/tokaido#108]
When enabling xdebug using `tok config` or `tok-config` set, the `xdebug:true` value is applied to the .tok/config.yml file, but the required xdebug _config_ is not added to the `system` tree: 

```
system:
  xdebug:
    port: "9000"
    enabled: true
    autostart: true
```

Thanks to @BenG for helping us identify this issue.
