### ISSUE TITLE
User-specific settings are leaking into config.yml

### ISSUE THREAD

**Issue by otakumike** [ironstar-io/tokaido#185]
The 'system' branch is leaking into config.yml in Tokaido 1.9. eg: 

```
system:
  syncsvc:
    systemdpath: /Users/username/.config/systemd/user
    launchdpath: /Users/username/Library/LaunchAgents
    enabled: true
  proxy:
    enabled: true
```

These values should be part of global.yml or removed entirely (most are out of date)
