### ISSUE TITLE
Max allowed packet size in MySQL

### ISSUE THREAD

**Issue by Benjen** [ironstar-io/tokaido#20]
**Is your feature request related to a problem? Please describe.**
No. 

**Describe the solution you'd like**
I was looking at my Drupal 7 site status page an noticed a message about the max allowed packet size in MySQL. It is currently set at '4M' but recommends setting it to at least '16M'. Was wondering if this is something which should be increased and set as default in the MySQL container config.

**Describe alternatives you've considered**
N/A

**Additional context**
![screen shot 2018-08-17 at 12 00 15 pm](https://user-images.githubusercontent.com/1292616/44245194-f0f15f80-a21a-11e8-9bfe-f77678afb9bd.png)

**Comment by otakumike** [comment]
Good point Ben. I've updated this in our docker-compose builder to set the default to 64MB moving forward:

```
mysql:
    image: mysql:5.7
    ports:
    - "3306"
    command: --max_allowed_packet=67108864
    environment:
      MYSQL_DATABASE: tokaido
      MYSQL_PASSWORD: tokaido
      MYSQL_ROOT_PASSWORD: tokaido
      MYSQL_USER: tokaido
```

This is what we use in Production and I think represents a sane default. In the next version (releasing Sunday) you'll be able to set this and any other MySQL-level parameters by setting up custom `command` parameters for MySQL. 

For example by adding the following to your `.tok/config.yml` file you could specify the default max_allowed_packet to 16MB :

```
services:
  mysql:
    command: --max-allowed-packet 16777216
```

Thanks as always for your great suggestions!!

Richo
